# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: design.gov.ro
author: GovITHub
email: design@ithub.gov.ro
description: > # this means to ignore newlines until "baseurl:"
  Ghid de proiectare a serviciilor gov.ro
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: govithub_ro
github_username:  gov-ithub

nav_main:
- page: Principii
  permalink: '/govro-design'
- page: UX
  permalink: '/govro-design/ux'
- page: UI
  permalink: '/govro-design/ui'
- page: Componente
  permalink: '/govro-design/componente'
- page: Utilizare
  permalink: '/govro-design/utilizare'

nav_principii:
- page: Principii generale
  permalink: '/govro-design/'
- page: Principii de UX
  permalink: '/govro-design/ux'
- page: Principii de UI
  permalink: '/govro-design/ui'

nav_ux:
  - page: Arhitectura Informației
    permalink: '#1-arhitectura-informației-ia'
  - page: User Experience Research
    permalink: '#2-user-experience-research-ux-research'
  - page: Interaction Design (IxD)
    permalink: '#3-interaction-design-ixd'

nav_ui:
  - page: Așezare în pagină
    permalink: '#1-așezare-în-pagină'
  - page: Tipografie
    permalink: '#2-tipografie'
  - page: Culori
    permalink: '#3-culori'
  - page: Pictograme și imagini
    permalink: '#4-pictograme-și-imagini'
  - page: Date
    permalink: '#5-date'
  - page: Butoane
    permalink: '#6-butoane'
  - page: Formulare
    permalink: '#7-formulare'
  - page: Erori și validare
    permalink: '#8-erori-și-validare'
  - page: Antet și subsol
    permalink: '#9-antet-și-subsol'

nav_componente:
- page: Așezare în pagină
  permalink: '#așezare-în-pagină'
- page: Tipografie
  permalink: '#tipografie'
- page: Butoane
  permalink: '#butoane'
- page: Formulare
  permalink: '#formulare'
- page: Navigație
  permalink: '#navigație'
- page: Alerte și notificări
  permalink: '#alerte-și-notificări'
- page: Starea implicită
  permalink: '#starea-implicită'
- page: Utilitare
  permalink: '#utilitare'
- page: Șabloane
  permalink: '#șabloane'

nav_utilizare:
- page: Pentru dezvoltatori
  permalink: '#pentru-dezvoltatori'
- page: Pentru designeri
  permalink: '#pentru-designeri'

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
